# Railway IaC Configuration for Frontend Service
[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"
watchPatterns = [
  "**/*"
]

[deploy]
startCommand = "PORT=${PORT:-3000} yarn start"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3