# Railway IaC Configuration for Worker Service
[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"
watchPatterns = [
  "app/background/**",
  "app/services/**", 
  "app/core/**",
  "pyproject.toml"
]

[deploy]
startCommand = "uv run worker"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5