# Railway IaC Configuration for Backend Service
[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"
watchPatterns = [
  "**/*"
]

[deploy]
preDeployCommand = "uv run prisma migrate deploy && uv run upsert-initial-plans"
startCommand = "uv run uvicorn app.main:app --host \"0.0.0.0:$PORT\""
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3