name: Deploy to Railway

on:
  push:
  workflow_dispatch:
    # branches: [ main, develop ]
  # pull_request:
  #   branches: [ main ]

jobs:
  deploy:
    name: Deploy to Railway
    runs-on: ubuntu-latest
    container: ghcr.io/railwayapp/cli:latest
    environment: MVP  # GitHub Environmentを指定
    
    env:
      CI: true
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
      RAILWAY_PROJECT_ID: ${{ secrets.RAILWAY_PROJECT_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Create .env file
        run: |
          cat > .env << EOF
          RAILWAY_TOKEN=${{ secrets.RAILWAY_TOKEN }}
          R2_ENDPOINT=${{ secrets.R2_ENDPOINT }}
          R2_ACCESS_KEY_ID=${{ secrets.R2_ACCESS_KEY_ID }}
          R2_SECRET_ACCESS_KEY=${{ secrets.R2_SECRET_ACCESS_KEY }}
          R2_BUCKET_NAME=${{ secrets.R2_BUCKET_NAME }}
          SECRET_KEY=${{ secrets.SECRET_KEY }}
          IP_HASH_SALT=${{ secrets.IP_HASH_SALT }}
          AUTH0_DOMAIN=${{ secrets.AUTH0_DOMAIN }}
          AUTH0_AUDIENCE=${{ secrets.AUTH0_AUDIENCE }}
          NEXT_PUBLIC_AUTH0_DOMAIN=${{ secrets.NEXT_PUBLIC_AUTH0_DOMAIN }}
          NEXT_PUBLIC_AUTH0_CLIENT_ID=${{ secrets.NEXT_PUBLIC_AUTH0_CLIENT_ID }}
          NEXT_PUBLIC_AUTH0_AUDIENCE=${{ secrets.NEXT_PUBLIC_AUTH0_AUDIENCE }}
          NEXT_PUBLIC_API_URL=https://securepass-back-mvp.up.railway.app
          EOF

      - name: Deploy to Railway
        run: |
          echo "Railway CLI version:"
          railway --version
          
          # トークンとプロジェクトIDが設定されているか確認
          echo "Checking configuration..."
          if [ -z "$RAILWAY_TOKEN" ]; then
            echo "RAILWAY_TOKEN is not set"
            exit 1
          else
            echo "RAILWAY_TOKEN is set (length: ${#RAILWAY_TOKEN})"
          fi
          
          if [ -z "$RAILWAY_PROJECT_ID" ]; then
            echo "RAILWAY_PROJECT_ID is not set"
            exit 1
          else
            echo "RAILWAY_PROJECT_ID is set: $RAILWAY_PROJECT_ID"
          fi
          
      - name: Deploy to Railway Services
        run: |
          echo "Railway CLI version:"
          railway --version
          
          echo "Deploying to existing Railway services..."
          echo "Note: Services must be created manually in Railway dashboard first"
          
          # 各サービスをデプロイ
          echo "Deploying backend..."
          cd backend && railway up --service backend --detach && cd .. || echo "Backend deployment failed - ensure 'backend' service exists in Railway"
          
          echo "Deploying frontend..."
          cd frontend && railway up --service frontend --detach && cd .. || echo "Frontend deployment failed - ensure 'frontend' service exists in Railway"
          
          echo "Deploying worker..."  
          cd backend && railway up --service worker --detach && cd .. || echo "Worker deployment failed - ensure 'worker' service exists in Railway"
          
          echo "All deployments completed"
