name: Deploy to Railway

on:
  push:
  workflow_dispatch:
    # branches: [ main, develop ]
  # pull_request:
  #   branches: [ main ]

jobs:
  deploy:
    name: Deploy to Railway
    runs-on: ubuntu-latest
    environment: MVP  # GitHub Environmentを指定
    
    # デプロイは main ブランチへのプッシュ時のみ実行
    # if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    env:
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
      CI: true  # CI環境を明示的に設定

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'yarn'
          cache-dependency-path: 'frontend/yarn.lock'

      - name: Install Railway CLI
        run: |
          # 最新の安定版をインストール
          curl -fsSL https://railway.app/install.sh | sh
          echo "$HOME/.railway/bin" >> $GITHUB_PATH
          
          # インストール後の確認
          railway --version

      - name: Install frontend dependencies
        run: |
          cd frontend
          yarn install

      - name: Deploy Backend Service
        run: |
          # railway.tomlの設定に基づいてサービスを自動作成・デプロイ
          echo "Deploying backend service..."
          railway up backend
          if [ $? -eq 0 ]; then
            echo "Backend deployment successful"
          else
            echo "Backend deployment failed"
            exit 1
          fi

      - name: Deploy Worker Service
        run: |
          echo "Deploying worker service..."
          railway up worker
          if [ $? -eq 0 ]; then
            echo "Worker deployment successful"
          else
            echo "Worker deployment failed"
            exit 1
          fi

      - name: Deploy Frontend Service  
        run: |
          echo "Deploying frontend service..."
          railway up frontend
          if [ $? -eq 0 ]; then
            echo "Frontend deployment successful"
          else
            echo "Frontend deployment failed" 
            exit 1
          fi

      - name: Deploy Backend Service
        run: |
          railway service --name backend
          
          # データベースURLを動的に取得して設定
          # PostgreSQL URLを取得
          railway service --name postgresql
          POSTGRES_URL=$(railway variables --kv | grep DATABASE_URL | cut -d'=' -f2)
          
          # Redis URLを取得
          railway service --name redis  
          REDIS_URL=$(railway variables --kv | grep REDIS_URL | cut -d'=' -f2)
          
          # バックエンドサービスに戻って環境変数を設定
          railway service --name backend
          railway variables set DATABASE_URL="$POSTGRES_URL"
          railway variables set REDIS_URL="$REDIS_URL"
          railway variables set R2_ENDPOINT="${{ secrets.R2_ENDPOINT }}"
          railway variables set R2_ACCESS_KEY_ID="${{ secrets.R2_ACCESS_KEY_ID }}"
          railway variables set R2_SECRET_ACCESS_KEY="${{ secrets.R2_SECRET_ACCESS_KEY }}"
          railway variables set R2_BUCKET_NAME="${{ secrets.R2_BUCKET_NAME }}"
          railway variables set SECRET_KEY="${{ secrets.SECRET_KEY }}"
          railway variables set IP_HASH_SALT="${{ secrets.IP_HASH_SALT }}"
          railway variables set AUTH0_DOMAIN="${{ secrets.AUTH0_DOMAIN }}"
          railway variables set AUTH0_AUDIENCE="${{ secrets.AUTH0_AUDIENCE }}"
          
          # バックエンドをデプロイ
          railway deploy --service backend

      - name: Deploy Worker Service  
        run: |
          railway service --name worker
          
          # ワーカーサービスにデータベースURLを設定（バックエンドと同じ）
          # データベースURLを再取得
          railway service --name postgresql
          POSTGRES_URL=$(railway variables --kv | grep DATABASE_URL | cut -d'=' -f2)
          railway service --name redis
          REDIS_URL=$(railway variables --kv | grep REDIS_URL | cut -d'=' -f2)
          
          railway service --name worker
          railway variables set DATABASE_URL="$POSTGRES_URL"
          railway variables set REDIS_URL="$REDIS_URL"
          railway variables set R2_ENDPOINT="${{ secrets.R2_ENDPOINT }}"
          railway variables set R2_ACCESS_KEY_ID="${{ secrets.R2_ACCESS_KEY_ID }}"
          railway variables set R2_SECRET_ACCESS_KEY="${{ secrets.R2_SECRET_ACCESS_KEY }}"
          railway variables set R2_BUCKET_NAME="${{ secrets.R2_BUCKET_NAME }}"
          railway variables set SECRET_KEY="${{ secrets.SECRET_KEY }}"
          railway variables set IP_HASH_SALT="${{ secrets.IP_HASH_SALT }}"
          
          # ワーカーをデプロイ
          railway deploy --service worker

      - name: Generate API Client with Backend URL
        id: backend-url
        run: |
          # 既存のRailwayエンドポイントを使用
          BACKEND_URL="https://securepass-back-mvp.up.railway.app"
          echo "url=$BACKEND_URL" >> $GITHUB_OUTPUT
          echo "Backend URL: $BACKEND_URL"
          
          # API生成を実行
          cd frontend
          NEXT_PUBLIC_API_URL="$BACKEND_URL" yarn generate-api
          echo "API client generated successfully"

      - name: Deploy Frontend Service
        run: |
          railway service --name frontend
          
          # フロントエンド用の環境変数を設定
          railway variables set NEXT_PUBLIC_AUTH0_DOMAIN="${{ secrets.NEXT_PUBLIC_AUTH0_DOMAIN }}"
          railway variables set NEXT_PUBLIC_AUTH0_CLIENT_ID="${{ secrets.NEXT_PUBLIC_AUTH0_CLIENT_ID }}"
          railway variables set NEXT_PUBLIC_AUTH0_AUDIENCE="${{ secrets.NEXT_PUBLIC_AUTH0_AUDIENCE }}"
          railway variables set NEXT_PUBLIC_API_URL="https://securepass-back-mvp.up.railway.app"
          
          # フロントエンドをデプロイ
          railway deploy --service frontend

      - name: Wait for deployment completion
        run: |
          echo "Waiting for all services to be fully deployed..."
          sleep 60
          
          # 各サービスの状態を確認
          echo "=== Backend Status ==="
          railway service --name backend
          railway status
          
          echo "=== Frontend Status ==="
          railway service --name frontend  
          railway status
          
          echo "=== Worker Status ==="
          railway service --name worker
          railway status
          
          echo "=== Database Services Status ==="
          railway service --name postgresql
          railway status
          
          railway service --name redis
          railway status
