name: Deploy to Railway

on:
  push:
  workflow_dispatch:
    # branches: [ main, develop ]
  # pull_request:
  #   branches: [ main ]

jobs:
  deploy:
    name: Deploy to Railway
    runs-on: ubuntu-latest
    environment: MVP  # GitHub Environmentを指定
    
    env:
      CI: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Create .env file
        run: |
          cat > .env << EOF
          RAILWAY_TOKEN=${{ secrets.RAILWAY_TOKEN }}
          R2_ENDPOINT=${{ secrets.R2_ENDPOINT }}
          R2_ACCESS_KEY_ID=${{ secrets.R2_ACCESS_KEY_ID }}
          R2_SECRET_ACCESS_KEY=${{ secrets.R2_SECRET_ACCESS_KEY }}
          R2_BUCKET_NAME=${{ secrets.R2_BUCKET_NAME }}
          SECRET_KEY=${{ secrets.SECRET_KEY }}
          IP_HASH_SALT=${{ secrets.IP_HASH_SALT }}
          AUTH0_DOMAIN=${{ secrets.AUTH0_DOMAIN }}
          AUTH0_AUDIENCE=${{ secrets.AUTH0_AUDIENCE }}
          NEXT_PUBLIC_AUTH0_DOMAIN=${{ secrets.NEXT_PUBLIC_AUTH0_DOMAIN }}
          NEXT_PUBLIC_AUTH0_CLIENT_ID=${{ secrets.NEXT_PUBLIC_AUTH0_CLIENT_ID }}
          NEXT_PUBLIC_AUTH0_AUDIENCE=${{ secrets.NEXT_PUBLIC_AUTH0_AUDIENCE }}
          NEXT_PUBLIC_API_URL=https://securepass-back-mvp.up.railway.app
          EOF

      - name: Install Railway CLI and Deploy
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          # Railway CLIをインストール
          npm install -g @railway/cli@latest
          
          echo "Railway CLI version:"
          railway --version
          
          # 認証確認
          echo "Checking authentication..."
          railway whoami
          
          echo "Starting deployment..."
          # 直接デプロイ（サービス自動検出）
          railway up --detach

      - name: Check Deployment Status
        run: |
          echo "Deployment initiated successfully"
