name: Deploy to Railway

on:
  push:
  workflow_dispatch:
    # branches: [ main, develop ]
  # pull_request:
  #   branches: [ main ]

jobs:
  deploy:
    name: Deploy to Railway
    runs-on: ubuntu-latest
    container: ghcr.io/railwayapp/cli:latest
    environment: MVP  # GitHub Environmentを指定
    
    # デプロイは main ブランチへのプッシュ時のみ実行
    # if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    env:
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
      CI: true  # CI環境を明示的に設定

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js and Yarn
        run: |
          # Node.js 22をインストール
          curl -fsSL https://deb.nodesource.com/setup_22.x | bash -
          apt-get install -y nodejs
          
          # Yarnをインストール
          npm install -g yarn
          
          # バージョン確認
          node --version
          yarn --version

      - name: Install frontend dependencies
        run: |
          cd frontend
          yarn install

      - name: Deploy All Services
        run: |
          # Project IDとEnvironment IDでリンク
          railway link -p ${{ secrets.RAILWAY_PROJECT_ID }} -e ${{ secrets.RAILWAY_ENVIRONMENT_ID }}
          
          # 環境変数を設定
          railway variables set R2_ENDPOINT="${{ secrets.R2_ENDPOINT }}"
          railway variables set R2_ACCESS_KEY_ID="${{ secrets.R2_ACCESS_KEY_ID }}"
          railway variables set R2_SECRET_ACCESS_KEY="${{ secrets.R2_SECRET_ACCESS_KEY }}"
          railway variables set R2_BUCKET_NAME="${{ secrets.R2_BUCKET_NAME }}"
          railway variables set SECRET_KEY="${{ secrets.SECRET_KEY }}"
          railway variables set IP_HASH_SALT="${{ secrets.IP_HASH_SALT }}"
          railway variables set AUTH0_DOMAIN="${{ secrets.AUTH0_DOMAIN }}"
          railway variables set AUTH0_AUDIENCE="${{ secrets.AUTH0_AUDIENCE }}"
          railway variables set NEXT_PUBLIC_AUTH0_DOMAIN="${{ secrets.NEXT_PUBLIC_AUTH0_DOMAIN }}"
          railway variables set NEXT_PUBLIC_AUTH0_CLIENT_ID="${{ secrets.NEXT_PUBLIC_AUTH0_CLIENT_ID }}"
          railway variables set NEXT_PUBLIC_AUTH0_AUDIENCE="${{ secrets.NEXT_PUBLIC_AUTH0_AUDIENCE }}"
          railway variables set NEXT_PUBLIC_API_URL="https://securepass-back-mvp.up.railway.app"
          
          # すべてのサービスをデプロイ
          railway deploy

      - name: Generate API Client
        run: |
          # API生成を実行
          cd frontend
          NEXT_PUBLIC_API_URL="https://securepass-back-mvp.up.railway.app" yarn generate-api
          echo "API client generated successfully"

      - name: Check Deployment Status
        run: |
          echo "Checking deployment status..."
          railway status
