name: Deploy to Railway

on:
  push:
  workflow_dispatch:
    # branches: [ main, develop ]
  # pull_request:
  #   branches: [ main ]

jobs:
  deploy:
    name: Deploy to Railway
    runs-on: ubuntu-latest
    container: ghcr.io/railwayapp/cli:latest
    environment: MVP  # GitHub Environmentを指定
    
    env:
      CI: true
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
      RAILWAY_PROJECT_ID: ${{ secrets.RAILWAY_PROJECT_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4



          
      - name: Configure Environment Variables
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          REDIS_URL: ${{ secrets.REDIS_URL }}
          R2_ENDPOINT: ${{ secrets.R2_ENDPOINT }}
          R2_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
          R2_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          R2_BUCKET_NAME: ${{ secrets.R2_BUCKET_NAME }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          IP_HASH_SALT: ${{ secrets.IP_HASH_SALT }}
          AUTH0_DOMAIN: ${{ secrets.AUTH0_DOMAIN }}
          AUTH0_AUDIENCE: ${{ secrets.AUTH0_AUDIENCE }}
          STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
          STRIPE_WEBHOOK_SECRET: ${{ secrets.STRIPE_WEBHOOK_SECRET }}
          STRIPE_PRO_PRICE_ID: ${{ secrets.STRIPE_PRO_PRICE_ID }}
          STRIPE_ENTERPRISE_PRICE_ID: ${{ secrets.STRIPE_ENTERPRISE_PRICE_ID }}
          NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
          NEXT_PUBLIC_AUTH0_DOMAIN: ${{ secrets.NEXT_PUBLIC_AUTH0_DOMAIN }}
          NEXT_PUBLIC_AUTH0_CLIENT_ID: ${{ secrets.NEXT_PUBLIC_AUTH0_CLIENT_ID }}
          NEXT_PUBLIC_AUTH0_AUDIENCE: ${{ secrets.NEXT_PUBLIC_AUTH0_AUDIENCE }}
        run: |
          echo "Configuring environment variables for each service..."
          
          # Backend環境変数設定（一括設定）
          echo "Setting backend environment variables..."
          railway variables --service backend \
            --set "DATABASE_URL=\${{ Postgres.DATABASE_URL }}" \
            --set "REDIS_URL=\${{ Redis.REDIS_URL }}" \
            --set "R2_ENDPOINT=${R2_ENDPOINT}" \
            --set "R2_ACCESS_KEY_ID=${R2_ACCESS_KEY_ID}" \
            --set "R2_SECRET_ACCESS_KEY=${R2_SECRET_ACCESS_KEY}" \
            --set "R2_BUCKET_NAME=${R2_BUCKET_NAME}" \
            --set "SECRET_KEY=${SECRET_KEY}" \
            --set "IP_HASH_SALT=${IP_HASH_SALT}" \
            --set "ENVIRONMENT=production" \
            --set "AUTH0_DOMAIN=${AUTH0_DOMAIN}" \
            --set "AUTH0_AUDIENCE=${AUTH0_AUDIENCE}" \
            --set "STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}" \
            --set "STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}" \
            --set "STRIPE_PRO_PRICE_ID=${STRIPE_PRO_PRICE_ID}" \
            --set "STRIPE_ENTERPRISE_PRICE_ID=${STRIPE_ENTERPRISE_PRICE_ID}"
          
          # Frontend環境変数設定（一括設定）
          echo "Setting frontend environment variables..."
          railway variables --service frontend \
            --set "NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}" \
            --set "NEXT_PUBLIC_ENVIRONMENT=production" \
            --set "NEXT_PUBLIC_AUTH0_DOMAIN=${NEXT_PUBLIC_AUTH0_DOMAIN}" \
            --set "NEXT_PUBLIC_AUTH0_CLIENT_ID=${NEXT_PUBLIC_AUTH0_CLIENT_ID}" \
            --set "NEXT_PUBLIC_AUTH0_AUDIENCE=${NEXT_PUBLIC_AUTH0_AUDIENCE}"
          
          # Worker環境変数設定（一括設定）
          echo "Setting worker environment variables..."
          railway variables --service worker \
            --set "DATABASE_URL=\${{ Postgres.DATABASE_URL }}" \
            --set "REDIS_URL=\${{ Redis.REDIS_URL }}" \
            --set "R2_ENDPOINT=${R2_ENDPOINT}" \
            --set "R2_ACCESS_KEY_ID=${R2_ACCESS_KEY_ID}" \
            --set "R2_SECRET_ACCESS_KEY=${R2_SECRET_ACCESS_KEY}" \
            --set "R2_BUCKET_NAME=${R2_BUCKET_NAME}" \
            --set "SECRET_KEY=${SECRET_KEY}" \
            --set "IP_HASH_SALT=${IP_HASH_SALT}" \
            --set "ENVIRONMENT=production" \
            --set "AUTH0_DOMAIN=${AUTH0_DOMAIN}" \
            --set "AUTH0_AUDIENCE=${AUTH0_AUDIENCE}" \
            --set "STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}" \
            --set "STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}" \
            --set "STRIPE_PRO_PRICE_ID=${STRIPE_PRO_PRICE_ID}" \
            --set "STRIPE_ENTERPRISE_PRICE_ID=${STRIPE_ENTERPRISE_PRICE_ID}"

      - name: Deploy to Railway Services
        run: |
          echo "Railway CLI version:"
          railway --version
          
          echo "Deploying to existing Railway services..."
          
          # 各サービスを個別のrailway.tomlで設定してデプロイ
          echo "Deploying backend..."
          (cd backend && railway up --service backend --detach) || echo "Backend deployment failed"
          
          echo "Deploying frontend..."
          (cd frontend && railway up --service frontend --detach) || echo "Frontend deployment failed"
          
          echo "Deploying worker..."  
          (cd backend && cp railway-worker.toml railway.toml && railway up --service worker --detach && rm railway.toml) || echo "Worker deployment failed"
          
          echo "All deployments completed"
